### ISSUE TITLE
io-sim: MonadFail issue in 8.8.x and beyond (fix suggestion)

### ISSUE THREAD

**Issue by Heinrich-CH** [input-output-hk/ouroboros-network#2209]
Hello,

When trying to build the code on ghc 8.8.3 and 8.10.1, I get the following error:

```
Configuring io-sim-0.1.0.0...
Preprocessing library for io-sim-0.1.0.0..
Building library for io-sim-0.1.0.0..
[1 of 1] Compiling Control.Monad.IOSim ( src/Control/Monad/IOSim.hs, dist/build/Co                                                                               ntrol/Monad/IOSim.dyn_o )

src/Control/Monad/IOSim.hs:181:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
181 |     fail = MonadFail.fail
    |     ^^^^

src/Control/Monad/IOSim.hs:211:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
211 |     fail = MonadFail.fail
    |     ^^^^
==> ERROR: A failure occurred in build().
    Aborting...
```

Upon reading the [MonadFail Proposal](https://wiki.haskell.org/MonadFail_Proposal), in the section for "Adapting old code", I read that ```fail = MonadFail.fail``` can be safely deleted. Do I understand this correctly? Anyway, after deleting that line, the `io-sim` builds on 8.8.3 (with some warnings).

**Comment by mrBliss** [comment]
Note that we only support GHC 8.6.5 at the moment.

**Comment by Heinrich-CH** [comment]
I am aware, and successfully built on 8.6.5. Just trying to get some potential optimizations for ARM (which I also am aware is not officially supported).
Was my approach of deleting the error-inducing line appropriate?
