### PR TITLE
Fix to compile on ghc-8.10.2

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

File: typed-protocols-examples/src/Network/TypedProtocol/Codec.hs [hunk 1]
```diff
@@ -1,16 +1,16 @@
...
+{-# LANGUAGE FlexibleContexts      #-}
+{-# LANGUAGE GADTs                 #-}
+{-# LANGUAGE NamedFieldPuns        #-}
+{-# LANGUAGE PolyKinds             #-}
+{-# LANGUAGE RankNTypes            #-}
+{-# LANGUAGE ScopedTypeVariables   #-}
+{-# LANGUAGE TypeFamilies          #-}
+{-# LANGUAGE TypeInType            #-}
 -- @UndecidableInstances@ extension is required for defining @Show@ instance of
 -- @'AnyMessage'@.
```
Comment (coot) [inline typed-protocols-examples/src/Network/TypedProtocol/Codec.hs:11]: This comment should apply to `UndecidableInstances`

Comment (coot) [reply typed-protocols-examples/src/Network/TypedProtocol/Codec.hs:11]: And if we are this could you update it, it mentioned `'AnyMessage'` while it should `AnyMessageAndAgency'.

**Review by coot — DISMISSED** [review]
Could you split this commit into the syntactic and non-syntactic change.

File: typed-protocols-examples/src/Network/TypedProtocol/Codec.hs (hunk 1 above)
Comment (newhoggy) [reply typed-protocols-examples/src/Network/TypedProtocol/Codec.hs]: I looks like it is needed for both:

```
src/Network/TypedProtocol/Codec.hs:288:10: error:
    • The constraint ‘Show (Message ps st st')’
        is no smaller than the instance head ‘Show (AnyMessage ps)’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for ‘Show (AnyMessage ps)’
    |
288 | instance (forall st st'. Show (Message ps st st')) => Show (AnyMessage ps) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/TypedProtocol/Codec.hs:303:5: error:
    • The constraint ‘Show (ClientHasAgency st)’
        is no smaller than
        the instance head ‘Show (AnyMessageAndAgency ps)’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for ‘Show (AnyMessageAndAgency ps)’
    |
303 |     ( forall (st :: ps)            . Show (ClientHasAgency st)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

File: typed-protocols-examples/src/Network/TypedProtocol/Codec.hs [hunk 2]
```diff
@@ -299,11 +299,11 @@ data AnyMessageAndAgency ps where
...
-instance (forall st st'. ( Show (Message ps st st')
-                         , Show (ClientHasAgency st)
-                         , Show (ServerHasAgency st)
-                         ))
-         => Show (AnyMessageAndAgency ps) where
+instance
+    ( forall (st :: ps)            . Show (ClientHasAgency st)
+    , forall (st :: ps) (st' :: ps). Show (Message ps st st')
+    , forall (st :: ps)            . Show (ServerHasAgency st)
+    ) => Show (AnyMessageAndAgency ps) where
```
Comment (coot) [inline typed-protocols-examples/src/Network/TypedProtocol/Codec.hs:306]:
```suggestion
instance
    ( forall (st :: ps).             Show (ClientHasAgency st)
    , forall (st :: ps) (st' :: ps). Show (Message ps st st')
    , forall (st :: ps).             Show (ServerHasAgency st)
    ) => Show (AnyMessageAndAgency ps) where
```

**Review by coot — CHANGES_REQUESTED** [review]

File: typed-protocols-examples/src/Network/TypedProtocol/Codec.hs (hunk 2 above)
Comment (newhoggy) [reply typed-protocols-examples/src/Network/TypedProtocol/Codec.hs]: Fixed!

**Review by coot — APPROVED** [review]
Thanks :tada:

**Comment by mrBliss** [comment]
bors merge
